version: '3.8'

services: 
  mongodb:
    image: mongo:latest
    container_name: mongodb
    # ports:
    #   - "4100:27017"
    volumes: 
      - /root/data:/data/db
    env_file:
      - wedive-secret/mongo-config.env
    restart: always
    networks:
      - mongodb-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      interval: 1s
      timeout: 10s
      retries: 3
    command: mongod --replSet replication
  
  # mongodb-replica-1:
  #   image: mongo:latest
  #   container_name: mongodb-replica-1
  #   # ports:
  #   #   - "4101:27017"
  #   depends_on:
  #     - mongodb
  #   volumes: 
  #     - /root/data-replica-1:/data/db
  #   env_file:
  #     - wedive-secret/mongo-config.env
  #   restart: always
  #   networks:
  #     - mongodb-network
  #   command: mongod --replSet replication
      
  # mongodb-replica-2:
  #   image: mongo:latest
  #   container_name: mongodb-replica-2
  #   # ports:
  #   #   - "4102:27017"
  #   depends_on:
  #     - mongodb
  #   volumes: 
  #     - /root/data-replica-2:/data/db
  #   env_file:
  #     - wedive-secret/mongo-config.env
  #   restart: always
  #   networks:
  #     - mongodb-network
  #   command: mongod --replSet replication

  mongodb-replica-setup:
    container_name: mongodb-replica-setup
    image: mongodb-replica-setup
    build:
      context: replica
      dockerfile: Dockerfile
    depends_on:
      - mongodb
      # - mongodb-replica-1
      # - mongodb-replica-2
    networks:
      - mongodb-network

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    env_file: 
      - wedive-secret/mongo-express-secret.env
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      # - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      # - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_ROOT_USER}
      # - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_ROOT_PASSWORD}
      # - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      # - ME_CONFIG_MONGODB_AUTH_USERNAME=${MONGO_ROOT_USER}
      # - ME_CONFIG_MONGODB_AUTH_PASSWORD=${MONGO_ROOT_PASSWORD}
      - ME_CONFIG_OPTIONS_EDITORTHEME=ambiance
    ports:
      - "4200:8081"
    depends_on:
      - mongodb
      # - mongodb-replica-1
      # - mongodb-replica-2
    restart: unless-stopped
    networks:
      - mongodb-network

  backup-agent:
    container_name: backup-agent
    image: tiredofit/db-backup
    depends_on:
      - mongodb
    env_file: 
      - wedive-secret/db-backup-config.env
    volumes:
      - /root/backups:/backup
    restart: always
    networks:
      - mongodb-network

networks:
  mongodb-network:
    driver: bridge
    name: mongodb-network