version: '3.8'

services: 

  mongo:
    image: mongo:latest
    container_name: mongodb
    # ports:
    #   - "4100:27017"
    volumes: 
      - /root/data:/data/db
    environment: 
      # - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
      # - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=platform
    restart: unless-stopped
  
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    env_file: 
      - mongo-express-secret.env
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      # - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      # - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_ROOT_USER}
      # - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_ROOT_PASSWORD}
      # - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      # - ME_CONFIG_MONGODB_AUTH_USERNAME=${MONGO_ROOT_USER}
      # - ME_CONFIG_MONGODB_AUTH_PASSWORD=${MONGO_ROOT_PASSWORD}
      # - ME_CONFIG_BASICAUTH_USERNAME=${MONGOEXPRESS_LOGIN}
      # - ME_CONFIG_BASICAUTH_PASSWORD=${MONGOEXPRESS_PASSWORD}
    ports:
      - "4200:8081"
    depends_on:
      - mongo
    restart: unless-stopped

  example-db-backup:
    container_name: backup-agent
    image: tiredofit/db-backup
    env_file: 
      - db-backup-config.env
    volumes:
      - /root/backups:/backup
    restart: always